name = "mayumiyui"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "YUMI"
id = "57ba24ed79b04865b941a48f00446f55"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2098b37f-ed03-4bca-ba58-1e3a5df9b21a"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/mayumiyui/Aqua/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/mayumiyui/Aqua/refs/heads/master/web/mayumiwandi.html"
